# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Serve files via HTTP."
  homepage "https://github.com/tschaub/serve"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tschaub/serve/releases/download/v0.2.0/serve-darwin-amd64.tar.gz"
      sha256 "a59beb691f699b4b89ec0d2c2b233b8b467494f2faae10d45fa7c5dac4c7aa53"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tschaub/serve/releases/download/v0.2.0/serve-darwin-arm64.tar.gz"
      sha256 "e892f5bdaeafa9df727211abc01076927d58d03762686b85937920307bd0ebd5"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tschaub/serve/releases/download/v0.2.0/serve-linux-amd64.tar.gz"
      sha256 "4db26a8b6966b2a15bd5a5c9b8da7ab8bcaa017afd69bd433f9b449662de0877"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tschaub/serve/releases/download/v0.2.0/serve-linux-arm64.tar.gz"
      sha256 "d7bb742e80d0c3a7044f408f5d2ad4e34e4a0e984947c113870ed07b42e1f623"

      def install
        bin.install "serve"
      end
    end
  end

  test do
    system "#{bin}/serve --help"
  end
end
