# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Serve files via HTTP."
  homepage "https://github.com/tschaub/serve"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tschaub/serve/releases/download/v0.4.0/serve-darwin-amd64.tar.gz"
      sha256 "aa5fbed1156629b14897508f7a0bc5c74d208957164f0f5ff6164e51e2b26289"

      def install
        bin.install "serve"
      end
    end
    on_arm do
      url "https://github.com/tschaub/serve/releases/download/v0.4.0/serve-darwin-arm64.tar.gz"
      sha256 "4589b785f8c25f62d07d91364c3cba3ab5711f6ddd7056fb71b936e933a49135"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/serve/releases/download/v0.4.0/serve-linux-amd64.tar.gz"
        sha256 "a4ba790999dc35db3bf1195c22f344e2f283dffb1e5e635b4c61e4eb350700a1"

        def install
          bin.install "serve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/serve/releases/download/v0.4.0/serve-linux-arm64.tar.gz"
        sha256 "cc80b835815a5f42a8556fb790a9e667d8efcc003fbf88c1e90a52a7e2749804"

        def install
          bin.install "serve"
        end
      end
    end
  end

  test do
    system "#{bin}/serve --help"
  end
end
