# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Serve files via HTTP."
  homepage "https://github.com/tschaub/serve"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tschaub/serve/releases/download/v0.3.0/serve-darwin-amd64.tar.gz"
      sha256 "e84274d593b24f9a18aed7cea072b754b7543ff858658dbe8644bb1b38e3cc0e"

      def install
        bin.install "serve"
      end
    end
    on_arm do
      url "https://github.com/tschaub/serve/releases/download/v0.3.0/serve-darwin-arm64.tar.gz"
      sha256 "f98bcffac8a1187f95b85c588ea1207aa970e757400cb4ecffa7cb9e6833c753"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/serve/releases/download/v0.3.0/serve-linux-amd64.tar.gz"
        sha256 "c26f982932b8fc9a39725ea67409bf4a34170ce2e5a51a56d6e5efa0829a62ac"

        def install
          bin.install "serve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/serve/releases/download/v0.3.0/serve-linux-arm64.tar.gz"
        sha256 "8ce78ac8f7d829a11af3ac8a52e8e2650c9e137568f8d6b1b42794db8c5c0948"

        def install
          bin.install "serve"
        end
      end
    end
  end

  test do
    system "#{bin}/serve --help"
  end
end
