# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Caching proxy for offline demos."
  homepage "https://github.com/tschaub/stash"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tschaub/stash/releases/download/v0.4.0/stash-darwin-amd64.tar.gz"
      sha256 "ebee254b504ff57376edfe62638eeccdca69350b0faea0a3bc8660038f0d5865"

      def install
        bin.install "stash"
      end
    end
    on_arm do
      url "https://github.com/tschaub/stash/releases/download/v0.4.0/stash-darwin-arm64.tar.gz"
      sha256 "6492972ea5b2c1887bd5964f2e94fabf02e3823cfc46e9eb9513c32cd931de37"

      def install
        bin.install "stash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/stash/releases/download/v0.4.0/stash-linux-amd64.tar.gz"
        sha256 "d74110340c65dfe83e03a56b4e463cd961b95b45d6f150175fbb566a251cea5f"

        def install
          bin.install "stash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/stash/releases/download/v0.4.0/stash-linux-arm64.tar.gz"
        sha256 "65512c4a0aaa13dd1db7d98fac56ed626071f7c7fccccee6892298576db58523"

        def install
          bin.install "stash"
        end
      end
    end
  end

  test do
    system "#{bin}/stash --help"
  end
end
