# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Caching proxy for offline demos."
  homepage "https://github.com/tschaub/stash"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tschaub/stash/releases/download/v0.5.0/stash-darwin-amd64.tar.gz"
      sha256 "a46fae09d4ceaecbbc28de2ab2be76ed3a20233787bb713db300efd669b75c0a"

      def install
        bin.install "stash"
      end
    end
    on_arm do
      url "https://github.com/tschaub/stash/releases/download/v0.5.0/stash-darwin-arm64.tar.gz"
      sha256 "6520f9b1fbf0f380460816d2d1354b8004d582242fcd169f9c48b7b10faef749"

      def install
        bin.install "stash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/stash/releases/download/v0.5.0/stash-linux-amd64.tar.gz"
        sha256 "ef90c7f55185704de506ae09f261378a61bcc1a437e094760ce6ee9552efff44"

        def install
          bin.install "stash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/stash/releases/download/v0.5.0/stash-linux-arm64.tar.gz"
        sha256 "fcb2678cc3ce88ece17b17d5227cc7e2a378b70359ac6cdd599ab0ea79ceb28f"

        def install
          bin.install "stash"
        end
      end
    end
  end

  test do
    system "#{bin}/stash --help"
  end
end
