# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Caching proxy for offline demos."
  homepage "https://github.com/tschaub/stash"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tschaub/stash/releases/download/v0.6.0/stash-darwin-amd64.tar.gz"
      sha256 "6d243c7917c460b9f83dc084a36d570ec07a167e1be142c1cc47338b6692297c"

      def install
        bin.install "stash"
      end
    end
    on_arm do
      url "https://github.com/tschaub/stash/releases/download/v0.6.0/stash-darwin-arm64.tar.gz"
      sha256 "89a1f51d17f10da393b2e4b24727b166ffbd169b814c7beccd23f6b47e964454"

      def install
        bin.install "stash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/stash/releases/download/v0.6.0/stash-linux-amd64.tar.gz"
        sha256 "ce6d20312401b80585df920277c7e394801ece5e39bceab212005ee9e948f1f3"

        def install
          bin.install "stash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tschaub/stash/releases/download/v0.6.0/stash-linux-arm64.tar.gz"
        sha256 "a31ba6b6272baa8b9aef5b43c37389a8a8678e77f0af8b2b96d0a8001b346aaa"

        def install
          bin.install "stash"
        end
      end
    end
  end

  test do
    system "#{bin}/stash --help"
  end
end
